name: devenv-anomalydetector
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.10.1
  - torchvision=0.11.2
  - scikit-learn=1.0.2
  - seaborn=0.11.2
  - pip=21.2.4
  - pip:
    - tqdm==4.62.3
    - hyperopt==0.2.7
    - azureml-core==1.40.0.post2
    - -r requirements.txt